AppBundle\Entity\Bateau:
  attributes:
    id:
      groups: ['bateau']
    nom:
      groups: ['bateau']
    anneecreation:
      groups: ['bateau']
    histoire:
      groups: ['bateau']
    image:
      groups: ['bateau']
    lat:
      groups: ['bateau']
    lng:
      groups: ['bateau']
    temoins:
      groups: ['bateau']

AppBundle\Entity\Temoin:
  attributes:
    id:
      groups: ['temoin','bateau']
    nom:
      groups: ['temoin','bateau']
    prenom:
      groups: ['temoin','bateau']
    profession:
      groups: ['temoin','bateau']
    photo_temoin:
      groups: ['temoin','bateau']
    temoignages:
      groups: ['temoin','bateau']

AppBundle\Entity\Temoignage:
  attributes:
    id:
      groups: ['temoin','bateau','temoignage']
    titre:
      groups: ['temoin','bateau']
    photo_temoignage:
      groups: ['temoin','bateau','temoignage']
    commentaire:
      groups: ['temoin','bateau']




