AppBundle\Entity\Musee:
  attributes:
    id:
      groups: ['musee']
    nom:
      groups: ['musee']
    adresse:
      groups: ['musee']
    horaire_ouverture:
      groups: ['musee']
    horaire_fermeture:
      groups: ['musee']

AppBundle\Entity\Bateau:
  attributes:
    id:
      groups: ['bateau']
    nom:
      groups: ['bateau']
    anneecreation:
      groups: ['bateau']
    histoire:
      groups: ['bateau']
    image:
      groups: ['bateau']
    lat:
      groups: ['bateau']
    lng:
      groups: ['bateau']
    musee:
      groups:
    temoins:
      groups: ['bateau']

AppBundle\Entity\Temoin:
  attributes:
    id:
      groups: ['temoin','bateau']
    nom:
      groups: ['temoin','bateau']
    prenom:
      groups: ['temoin','bateau']
    temoignages:
      groups: ['temoin']

AppBundle\Entity\Temoignage:
  attributes:
    id:
      groups: ['temoignage','temoin']
    titre:
      groups: ['temoignage','temoin']
    photo_temoignage:
      groups: ['temoignage','temoin']
    commentaire:
      groups: ['temoignage','temoin']




